create table Reading_card(
    id INTEGER UNSIGNED PRIMARY KEY AUTOINCREMENT UNIQUE ,
    user_id INTEGER UNSIGNED NOT NULL,
    clock_in TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OTP INTEGER UNIQUE NOT NULL 
);

create table users(
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
    rfid_uid VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);